[[redirects]]
  from = "/api/*"
  to = "http://46.1.103.229:8080/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}




[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

