[[redirects]]
  from = "/api/*"
  to = "https://api.bilgehan26.keenetic.pro/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}




[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

